# Name: Tessa Melli 
# Date: 4/25/23
# Course: CS493-400
# Assignment: Assignment 3 - Build a Restful API


# ***** BEGIN CITED CODE *****
# The following code is not my own
# SOURCE: https://canvas.oregonstate.edu/courses/1915173/files/98341639?wrap=1
# Description: configuration file that defines runtime and handler settings for App Engine

runtime: python39

handlers:
  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

    # ***** END CITED CODE ********